### ISSUE TITLE
After it fills out the date for creating an account it stops

### ISSUE THREAD

**Issue by Hushhh12** [Necrownyx/Twitch-Account-Creator#13]
Hello, it doesnt do anything after it fills out the date for the account so I don't know if the account was created or not

**Comment by Necrownyx** [comment]
this is a preprogrammed stop in the program put in place due to an issue some users are facing where the account is unable to be automatically created due to twitch's bot protection.

if you wish to re enable this button click you can add an extra live to the end of the final function to click it.

Link to documentation to help: https://selenium-python.readthedocs.io/locating-elements.html
